CREATE DATABASE blogs_db;
USE blogs_db;

CREATE TABLE blogs(
	id INT AUTO_INCREMENT NOT NULL,
    author VARCHAR (30) NOT NULL,
    dates DATETIME,
    text VARCHAR(450) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE comments(
	id INT AUTO_INCREMENT NOT NULL,
    blogId INT NOT NULL,
    text VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);